/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SerialsRouteImport } from './routes/serials'
import { Route as RfidRouteImport } from './routes/rfid'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OpacRouteImport } from './routes/opac'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as CirculationRouteImport } from './routes/circulation'
import { Route as CatalogingRouteImport } from './routes/cataloging'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcquisitionsRouteImport } from './routes/acquisitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatronsIdRouteImport } from './routes/patrons.$id'
import { Route as OpacIdRouteImport } from './routes/opac.$id'
import { Route as CatalogingIdRouteImport } from './routes/cataloging.$id'
import { Route as AcquisitionsIdRouteImport } from './routes/acquisitions.$id'

const SerialsRoute = SerialsRouteImport.update({
  id: '/serials',
  path: '/serials',
  getParentRoute: () => rootRouteImport,
} as any)
const RfidRoute = RfidRouteImport.update({
  id: '/rfid',
  path: '/rfid',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OpacRoute = OpacRouteImport.update({
  id: '/opac',
  path: '/opac',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const CirculationRoute = CirculationRouteImport.update({
  id: '/circulation',
  path: '/circulation',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogingRoute = CatalogingRouteImport.update({
  id: '/cataloging',
  path: '/cataloging',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsRoute = AcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronsIdRoute = PatronsIdRouteImport.update({
  id: '/patrons/$id',
  path: '/patrons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpacIdRoute = OpacIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpacRoute,
} as any)
const CatalogingIdRoute = CatalogingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogingRoute,
} as any)
const AcquisitionsIdRoute = AcquisitionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcquisitionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRouteWithChildren
  '/admin': typeof AdminRoute
  '/cataloging': typeof CatalogingRouteWithChildren
  '/circulation': typeof CirculationRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/opac': typeof OpacRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rfid': typeof RfidRoute
  '/serials': typeof SerialsRoute
  '/acquisitions/$id': typeof AcquisitionsIdRoute
  '/cataloging/$id': typeof CatalogingIdRoute
  '/opac/$id': typeof OpacIdRoute
  '/patrons/$id': typeof PatronsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRouteWithChildren
  '/admin': typeof AdminRoute
  '/cataloging': typeof CatalogingRouteWithChildren
  '/circulation': typeof CirculationRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/opac': typeof OpacRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rfid': typeof RfidRoute
  '/serials': typeof SerialsRoute
  '/acquisitions/$id': typeof AcquisitionsIdRoute
  '/cataloging/$id': typeof CatalogingIdRoute
  '/opac/$id': typeof OpacIdRoute
  '/patrons/$id': typeof PatronsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRouteWithChildren
  '/admin': typeof AdminRoute
  '/cataloging': typeof CatalogingRouteWithChildren
  '/circulation': typeof CirculationRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/opac': typeof OpacRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rfid': typeof RfidRoute
  '/serials': typeof SerialsRoute
  '/acquisitions/$id': typeof AcquisitionsIdRoute
  '/cataloging/$id': typeof CatalogingIdRoute
  '/opac/$id': typeof OpacIdRoute
  '/patrons/$id': typeof PatronsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisitions'
    | '/admin'
    | '/cataloging'
    | '/circulation'
    | '/glossary'
    | '/login'
    | '/opac'
    | '/reports'
    | '/rfid'
    | '/serials'
    | '/acquisitions/$id'
    | '/cataloging/$id'
    | '/opac/$id'
    | '/patrons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisitions'
    | '/admin'
    | '/cataloging'
    | '/circulation'
    | '/glossary'
    | '/login'
    | '/opac'
    | '/reports'
    | '/rfid'
    | '/serials'
    | '/acquisitions/$id'
    | '/cataloging/$id'
    | '/opac/$id'
    | '/patrons/$id'
  id:
    | '__root__'
    | '/'
    | '/acquisitions'
    | '/admin'
    | '/cataloging'
    | '/circulation'
    | '/glossary'
    | '/login'
    | '/opac'
    | '/reports'
    | '/rfid'
    | '/serials'
    | '/acquisitions/$id'
    | '/cataloging/$id'
    | '/opac/$id'
    | '/patrons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionsRoute: typeof AcquisitionsRouteWithChildren
  AdminRoute: typeof AdminRoute
  CatalogingRoute: typeof CatalogingRouteWithChildren
  CirculationRoute: typeof CirculationRoute
  GlossaryRoute: typeof GlossaryRoute
  LoginRoute: typeof LoginRoute
  OpacRoute: typeof OpacRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RfidRoute: typeof RfidRoute
  SerialsRoute: typeof SerialsRoute
  PatronsIdRoute: typeof PatronsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/serials': {
      id: '/serials'
      path: '/serials'
      fullPath: '/serials'
      preLoaderRoute: typeof SerialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfid': {
      id: '/rfid'
      path: '/rfid'
      fullPath: '/rfid'
      preLoaderRoute: typeof RfidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opac': {
      id: '/opac'
      path: '/opac'
      fullPath: '/opac'
      preLoaderRoute: typeof OpacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulation': {
      id: '/circulation'
      path: '/circulation'
      fullPath: '/circulation'
      preLoaderRoute: typeof CirculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cataloging': {
      id: '/cataloging'
      path: '/cataloging'
      fullPath: '/cataloging'
      preLoaderRoute: typeof CatalogingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrons/$id': {
      id: '/patrons/$id'
      path: '/patrons/$id'
      fullPath: '/patrons/$id'
      preLoaderRoute: typeof PatronsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opac/$id': {
      id: '/opac/$id'
      path: '/$id'
      fullPath: '/opac/$id'
      preLoaderRoute: typeof OpacIdRouteImport
      parentRoute: typeof OpacRoute
    }
    '/cataloging/$id': {
      id: '/cataloging/$id'
      path: '/$id'
      fullPath: '/cataloging/$id'
      preLoaderRoute: typeof CatalogingIdRouteImport
      parentRoute: typeof CatalogingRoute
    }
    '/acquisitions/$id': {
      id: '/acquisitions/$id'
      path: '/$id'
      fullPath: '/acquisitions/$id'
      preLoaderRoute: typeof AcquisitionsIdRouteImport
      parentRoute: typeof AcquisitionsRoute
    }
  }
}

interface AcquisitionsRouteChildren {
  AcquisitionsIdRoute: typeof AcquisitionsIdRoute
}

const AcquisitionsRouteChildren: AcquisitionsRouteChildren = {
  AcquisitionsIdRoute: AcquisitionsIdRoute,
}

const AcquisitionsRouteWithChildren = AcquisitionsRoute._addFileChildren(
  AcquisitionsRouteChildren,
)

interface CatalogingRouteChildren {
  CatalogingIdRoute: typeof CatalogingIdRoute
}

const CatalogingRouteChildren: CatalogingRouteChildren = {
  CatalogingIdRoute: CatalogingIdRoute,
}

const CatalogingRouteWithChildren = CatalogingRoute._addFileChildren(
  CatalogingRouteChildren,
)

interface OpacRouteChildren {
  OpacIdRoute: typeof OpacIdRoute
}

const OpacRouteChildren: OpacRouteChildren = {
  OpacIdRoute: OpacIdRoute,
}

const OpacRouteWithChildren = OpacRoute._addFileChildren(OpacRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionsRoute: AcquisitionsRouteWithChildren,
  AdminRoute: AdminRoute,
  CatalogingRoute: CatalogingRouteWithChildren,
  CirculationRoute: CirculationRoute,
  GlossaryRoute: GlossaryRoute,
  LoginRoute: LoginRoute,
  OpacRoute: OpacRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RfidRoute: RfidRoute,
  SerialsRoute: SerialsRoute,
  PatronsIdRoute: PatronsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
